builds:
  - binary: gigger
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - 
        goos: freebsd
        goarch: arm64
      - 
        goos: linux
        goarch: 386

archives:
  - id: tgz
    format: tar.gz
    replacements:
        darwin: macOS
    format_overrides:
        - goos: windows
          format: zip

signs:
  - artifacts: checksum